kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: ubuntu:18.04
    commands:
      - echo 'hello'
    when:
      event:
        - push
        - pull_request