kind: pipeline
name: default

steps:
  - name: install
    image: karuppiah7890/bashful
    commands:
      - bashful --version
      - make ARG=test01 sandbox-try && make ARG=test02 sandbox-try
      - make ARG=test01 sandbox-archive && [ -e data/archives/$(date -I)_sandbox_test01.tar.bz2 ] && echo 'OK'
      - make sandbox-archive-all && [ -e data/archives/$(date -I)_sandbox_all.tar.bz2 ] && echo 'OK'
    when:
      event:
        - push
        - pull_request