# dev.yml, see https://github.com/wagoodman/bashful

$include: config/common-config.yml

x-reference-data:
  all-dirs: &dir-names
    - $include config/common-dirs.yml

tasks:

###################
# Check Structure #
###################

    - name: 'Check dir (create dir if need): <replace>'
      cmd: '[ -e <replace> ] || mkdir <replace>'
      ignore-failure: true
      for-each: *dir-names
      tags: check

###########
# SANDBOX #
###########

    - name: Sandbox Create
      cmd: 'PATH_S=./data/sandbox/$1; [ -e ${PATH_S} ] || mkdir ${PATH_S}'
      tags: sandbox-create

    - name: Sandbox Delete
      cmd: 'PATH_S=./data/sandbox/$1; [ -e ${PATH_S} ] && rm -fr ${PATH_S}'
      tags: sandbox-delete

    - name: Sandbox Delete All
      cmd: 'PATH_S=./data/sandbox; [ -e ${PATH_S} ] && rm -fr ${PATH_S}/*'
      tags: sandbox-delete-all

    - name: Sandbox Archive
      cmd: 'PATH_S=./data/sandbox/$1; [ -e ${PATH_S} ] && tar -cvjf data/archives/$(date -I)_sandbox_$1.tar.bz2 ${PATH_S}'
      tags: sandbox-archive

    - name: Sandbox Archive All
      cmd: 'PATH_S=./data/sandbox; [ -e ${PATH_S} ] && tar -cvjf data/archives/$(date -I)_sandbox_all.tar.bz2 ${PATH_S}/*'
      tags: sandbox-archive-all
