name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: msdevlib/bashful-dev:0.1.1

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make test